import numpy as np
import math
import matplotlib.pyplot as plt

''' Metodo delle approssimazioni successive'''
def succ_app(f, g, tolf, tolx, maxit, xTrue, x0=0):
  
  err=np.zeros(maxit+1, dtype=np.float64)
  vecErrore=np.zeros(maxit+1, dtype=np.float64)
  
  
  i= ...
  err[0]=...
  vecErrore[0] = ...
  x = ...

  while (... ): 
    ...
    
  err = ...  
  vecErrore = ...
  return (x, i, err, vecErrore) 


'''creazione del problema'''
f = ...
df = ...

g1 = lambda x: x-f(x)...
g2 = ...
g3 = ...

xTrue = -0.7034674
fTrue = ...
print('fTrue = ', fTrue)

tolx= 10**(-10)
tolf = 10**(-6)
maxit=100
x0= 0


''' Grafico funzione in [-1, 1]'''

...


'''Calcolo soluzione cin g1, g2 e g3'''

...
print('Metodo approssimazioni successive g1 \n x =',...,'\n iter_new=', ...)

...
print('Metodo approssimazioni successive g2 \n x =',...,'\n iter_new=', ...)

...
print('Metodo approssimazioni successive g3 \n x =',...,'\n iter_new=', ...)


''' Grafico Errore vs Iterazioni'''
# g1
plt.plot(...
# g2
plt.plot(...
# g3
plt.plot(v...

...